[package]
name = "app"
version = "0.1.0"
description = "Chatting directly with friends"
authors = ["devensiv <devensiv@gmail.com>", "max <mx.coppen@gmail.com"]
license = ""
repository = ""
default-run = "app"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.0.0", features = [] }

[dependencies]
smoke = { git = "https://github.com/emberry-org/smoke" }
base64 = "0.13.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.0.0", features = ["api-all", "devtools"] }
# Used for adding back window shadows on transparent window
raw-window-handle = "0.4"
# Used for the environment variables
dotenv_codegen = "0.15.0"
# Tauri persistent store
tauri-plugin-store = { git = "https://github.com/tauri-apps/tauri-plugin-store", branch = "dev" }
# Async
tokio = { version = "1.18.2", features = ["net", "macros", "rt", "sync"] }
# Tls connection
tokio-rustls = "0.23"
rustls = { version = "0.20" }
rustls-pemfile = { version="0.2" }

[target."cfg(target_os = \"windows\")".dependencies]
windows-sys = { version = "0.36.1", features = [
  "Win32_Foundation",
  "Win32_Graphics_Dwm",
  "Win32_UI_Controls"
] }
window-vibrancy = "0.1.3"

[target."cfg(target_os = \"macos\")".dependencies]
cocoa = "0.24"
objc = "0.2"

[features]
# Debug code
debug = []
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = [ "custom-protocol", "debug"]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = [ "tauri/custom-protocol" ]
