[package]
name = "keygenerator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rcgen = { version = "0.9" }
rustls = { version = "0.20" }